//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("PersonalSiteDBModel", "FK_PSProjects_PSBizSolutions", "PSBizSolutions", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MvcPersonalSite.PSBizSolution), "PSProjects", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcPersonalSite.PSProject), true)]
[assembly: EdmRelationshipAttribute("PersonalSiteDBModel", "FK_PSProjects_PSCategories", "PSCategories", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcPersonalSite.PSCategory), "PSProjects", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcPersonalSite.PSProject), true)]
[assembly: EdmRelationshipAttribute("PersonalSiteDBModel", "FK_PSProjectTechTag_PSProjects", "PSProjects", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcPersonalSite.PSProject), "PSProjectTechTag", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcPersonalSite.PSProjectTechTag), true)]
[assembly: EdmRelationshipAttribute("PersonalSiteDBModel", "FK_PSProjectTechTag_PSTechTags", "PSTechTags", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcPersonalSite.PSTechTag), "PSProjectTechTag", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcPersonalSite.PSProjectTechTag), true)]

#endregion

namespace MvcPersonalSite
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class PersonalSiteDBEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new PersonalSiteDBEntities1 object using the connection string found in the 'PersonalSiteDBEntities1' section of the application configuration file.
        /// </summary>
        public PersonalSiteDBEntities1() : base("name=PersonalSiteDBEntities1", "PersonalSiteDBEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PersonalSiteDBEntities1 object.
        /// </summary>
        public PersonalSiteDBEntities1(string connectionString) : base(connectionString, "PersonalSiteDBEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PersonalSiteDBEntities1 object.
        /// </summary>
        public PersonalSiteDBEntities1(EntityConnection connection) : base(connection, "PersonalSiteDBEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PSBizSolution> PSBizSolutions
        {
            get
            {
                if ((_PSBizSolutions == null))
                {
                    _PSBizSolutions = base.CreateObjectSet<PSBizSolution>("PSBizSolutions");
                }
                return _PSBizSolutions;
            }
        }
        private ObjectSet<PSBizSolution> _PSBizSolutions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PSCategory> PSCategories
        {
            get
            {
                if ((_PSCategories == null))
                {
                    _PSCategories = base.CreateObjectSet<PSCategory>("PSCategories");
                }
                return _PSCategories;
            }
        }
        private ObjectSet<PSCategory> _PSCategories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PSProject> PSProjects
        {
            get
            {
                if ((_PSProjects == null))
                {
                    _PSProjects = base.CreateObjectSet<PSProject>("PSProjects");
                }
                return _PSProjects;
            }
        }
        private ObjectSet<PSProject> _PSProjects;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PSProjectTechTag> PSProjectTechTags
        {
            get
            {
                if ((_PSProjectTechTags == null))
                {
                    _PSProjectTechTags = base.CreateObjectSet<PSProjectTechTag>("PSProjectTechTags");
                }
                return _PSProjectTechTags;
            }
        }
        private ObjectSet<PSProjectTechTag> _PSProjectTechTags;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PSTechTag> PSTechTags
        {
            get
            {
                if ((_PSTechTags == null))
                {
                    _PSTechTags = base.CreateObjectSet<PSTechTag>("PSTechTags");
                }
                return _PSTechTags;
            }
        }
        private ObjectSet<PSTechTag> _PSTechTags;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PSBizSolutions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPSBizSolutions(PSBizSolution pSBizSolution)
        {
            base.AddObject("PSBizSolutions", pSBizSolution);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PSCategories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPSCategories(PSCategory pSCategory)
        {
            base.AddObject("PSCategories", pSCategory);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PSProjects EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPSProjects(PSProject pSProject)
        {
            base.AddObject("PSProjects", pSProject);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PSProjectTechTags EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPSProjectTechTags(PSProjectTechTag pSProjectTechTag)
        {
            base.AddObject("PSProjectTechTags", pSProjectTechTag);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PSTechTags EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPSTechTags(PSTechTag pSTechTag)
        {
            base.AddObject("PSTechTags", pSTechTag);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PersonalSiteDBModel", Name="PSBizSolution")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PSBizSolution : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PSBizSolution object.
        /// </summary>
        /// <param name="bizID">Initial value of the bizID property.</param>
        /// <param name="bizSolnName">Initial value of the bizSolnName property.</param>
        public static PSBizSolution CreatePSBizSolution(global::System.Int32 bizID, global::System.String bizSolnName)
        {
            PSBizSolution pSBizSolution = new PSBizSolution();
            pSBizSolution.bizID = bizID;
            pSBizSolution.bizSolnName = bizSolnName;
            return pSBizSolution;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 bizID
        {
            get
            {
                return _bizID;
            }
            set
            {
                if (_bizID != value)
                {
                    OnbizIDChanging(value);
                    ReportPropertyChanging("bizID");
                    _bizID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("bizID");
                    OnbizIDChanged();
                }
            }
        }
        private global::System.Int32 _bizID;
        partial void OnbizIDChanging(global::System.Int32 value);
        partial void OnbizIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String bizSolnName
        {
            get
            {
                return _bizSolnName;
            }
            set
            {
                OnbizSolnNameChanging(value);
                ReportPropertyChanging("bizSolnName");
                _bizSolnName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("bizSolnName");
                OnbizSolnNameChanged();
            }
        }
        private global::System.String _bizSolnName;
        partial void OnbizSolnNameChanging(global::System.String value);
        partial void OnbizSolnNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PersonalSiteDBModel", "FK_PSProjects_PSBizSolutions", "PSProjects")]
        public EntityCollection<PSProject> PSProjects
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PSProject>("PersonalSiteDBModel.FK_PSProjects_PSBizSolutions", "PSProjects");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PSProject>("PersonalSiteDBModel.FK_PSProjects_PSBizSolutions", "PSProjects", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PersonalSiteDBModel", Name="PSCategory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PSCategory : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PSCategory object.
        /// </summary>
        /// <param name="categoryID">Initial value of the categoryID property.</param>
        /// <param name="categoryName">Initial value of the categoryName property.</param>
        public static PSCategory CreatePSCategory(global::System.Int32 categoryID, global::System.String categoryName)
        {
            PSCategory pSCategory = new PSCategory();
            pSCategory.categoryID = categoryID;
            pSCategory.categoryName = categoryName;
            return pSCategory;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 categoryID
        {
            get
            {
                return _categoryID;
            }
            set
            {
                if (_categoryID != value)
                {
                    OncategoryIDChanging(value);
                    ReportPropertyChanging("categoryID");
                    _categoryID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("categoryID");
                    OncategoryIDChanged();
                }
            }
        }
        private global::System.Int32 _categoryID;
        partial void OncategoryIDChanging(global::System.Int32 value);
        partial void OncategoryIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String categoryName
        {
            get
            {
                return _categoryName;
            }
            set
            {
                OncategoryNameChanging(value);
                ReportPropertyChanging("categoryName");
                _categoryName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("categoryName");
                OncategoryNameChanged();
            }
        }
        private global::System.String _categoryName;
        partial void OncategoryNameChanging(global::System.String value);
        partial void OncategoryNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PersonalSiteDBModel", "FK_PSProjects_PSCategories", "PSProjects")]
        public EntityCollection<PSProject> PSProjects
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PSProject>("PersonalSiteDBModel.FK_PSProjects_PSCategories", "PSProjects");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PSProject>("PersonalSiteDBModel.FK_PSProjects_PSCategories", "PSProjects", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PersonalSiteDBModel", Name="PSProject")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PSProject : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PSProject object.
        /// </summary>
        /// <param name="projectID">Initial value of the projectID property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="category">Initial value of the category property.</param>
        public static PSProject CreatePSProject(global::System.Int32 projectID, global::System.String name, global::System.Int32 category)
        {
            PSProject pSProject = new PSProject();
            pSProject.projectID = projectID;
            pSProject.name = name;
            pSProject.category = category;
            return pSProject;
        }

        #endregion

        #region Primitive Properties

    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 projectID
        {
            get
            {
                return _projectID;
            }
            set
            {
                if (_projectID != value)
                {
                    OnprojectIDChanging(value);
                    ReportPropertyChanging("projectID");
                    _projectID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("projectID");
                    OnprojectIDChanged();
                }
            }
        }
        private global::System.Int32 _projectID;
        partial void OnprojectIDChanging(global::System.Int32 value);
        partial void OnprojectIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String url
        {
            get
            {
                return _url;
            }
            set
            {
                OnurlChanging(value);
                ReportPropertyChanging("url");
                _url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("url");
                OnurlChanged();
            }
        }
        private global::System.String _url;
        partial void OnurlChanging(global::System.String value);
        partial void OnurlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 category
        {
            get
            {
                return _category;
            }
            set
            {
                OncategoryChanging(value);
                ReportPropertyChanging("category");
                _category = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("category");
                OncategoryChanged();
            }
        }
        private global::System.Int32 _category;
        partial void OncategoryChanging(global::System.Int32 value);
        partial void OncategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String screenshot
        {
            get
            {
                return _screenshot;
            }
            set
            {
                OnscreenshotChanging(value);
                ReportPropertyChanging("screenshot");
                _screenshot = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("screenshot");
                OnscreenshotChanged();
            }
        }
        private global::System.String _screenshot;
        partial void OnscreenshotChanging(global::System.String value);
        partial void OnscreenshotChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> businessSolution
        {
            get
            {
                return _businessSolution;
            }
            set
            {
                OnbusinessSolutionChanging(value);
                ReportPropertyChanging("businessSolution");
                _businessSolution = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("businessSolution");
                OnbusinessSolutionChanged();
            }
        }
        private Nullable<global::System.Int32> _businessSolution;
        partial void OnbusinessSolutionChanging(Nullable<global::System.Int32> value);
        partial void OnbusinessSolutionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PersonalSiteDBModel", "FK_PSProjects_PSBizSolutions", "PSBizSolutions")]
        public PSBizSolution PSBizSolution
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PSBizSolution>("PersonalSiteDBModel.FK_PSProjects_PSBizSolutions", "PSBizSolutions").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PSBizSolution>("PersonalSiteDBModel.FK_PSProjects_PSBizSolutions", "PSBizSolutions").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PSBizSolution> PSBizSolutionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PSBizSolution>("PersonalSiteDBModel.FK_PSProjects_PSBizSolutions", "PSBizSolutions");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PSBizSolution>("PersonalSiteDBModel.FK_PSProjects_PSBizSolutions", "PSBizSolutions", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PersonalSiteDBModel", "FK_PSProjects_PSCategories", "PSCategories")]
        public PSCategory PSCategory
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PSCategory>("PersonalSiteDBModel.FK_PSProjects_PSCategories", "PSCategories").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PSCategory>("PersonalSiteDBModel.FK_PSProjects_PSCategories", "PSCategories").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PSCategory> PSCategoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PSCategory>("PersonalSiteDBModel.FK_PSProjects_PSCategories", "PSCategories");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PSCategory>("PersonalSiteDBModel.FK_PSProjects_PSCategories", "PSCategories", value);
                }
            }
        }
    
        /// <summary>
        /// This is the one I changed.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PersonalSiteDBModel", "FK_PSProjectTechTag_PSProjects", "PSProjectTechTag")]
        public EntityCollection<PSProjectTechTag> PSProjectTechTags
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PSProjectTechTag>("PersonalSiteDBModel.FK_PSProjectTechTag_PSProjects", "PSProjectTechTag");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PSProjectTechTag>("PersonalSiteDBModel.FK_PSProjectTechTag_PSProjects", "PSProjectTechTag", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PersonalSiteDBModel", Name="PSProjectTechTag")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PSProjectTechTag : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PSProjectTechTag object.
        /// </summary>
        /// <param name="projectID">Initial value of the projectID property.</param>
        /// <param name="techTagID">Initial value of the techTagID property.</param>
        public static PSProjectTechTag CreatePSProjectTechTag(global::System.Int32 projectID, global::System.Int32 techTagID)
        {
            PSProjectTechTag pSProjectTechTag = new PSProjectTechTag();
            pSProjectTechTag.projectID = projectID;
            pSProjectTechTag.techTagID = techTagID;
            return pSProjectTechTag;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 projectID
        {
            get
            {
                return _projectID;
            }
            set
            {
                if (_projectID != value)
                {
                    OnprojectIDChanging(value);
                    ReportPropertyChanging("projectID");
                    _projectID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("projectID");
                    OnprojectIDChanged();
                }
            }
        }
        private global::System.Int32 _projectID;
        partial void OnprojectIDChanging(global::System.Int32 value);
        partial void OnprojectIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 techTagID
        {
            get
            {
                return _techTagID;
            }
            set
            {
                if (_techTagID != value)
                {
                    OntechTagIDChanging(value);
                    ReportPropertyChanging("techTagID");
                    _techTagID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("techTagID");
                    OntechTagIDChanged();
                }
            }
        }
        private global::System.Int32 _techTagID;
        partial void OntechTagIDChanging(global::System.Int32 value);
        partial void OntechTagIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PersonalSiteDBModel", "FK_PSProjectTechTag_PSProjects", "PSProjects")]
        public PSProject PSProject
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PSProject>("PersonalSiteDBModel.FK_PSProjectTechTag_PSProjects", "PSProjects").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PSProject>("PersonalSiteDBModel.FK_PSProjectTechTag_PSProjects", "PSProjects").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PSProject> PSProjectReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PSProject>("PersonalSiteDBModel.FK_PSProjectTechTag_PSProjects", "PSProjects");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PSProject>("PersonalSiteDBModel.FK_PSProjectTechTag_PSProjects", "PSProjects", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PersonalSiteDBModel", "FK_PSProjectTechTag_PSTechTags", "PSTechTags")]
        public PSTechTag PSTechTag
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PSTechTag>("PersonalSiteDBModel.FK_PSProjectTechTag_PSTechTags", "PSTechTags").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PSTechTag>("PersonalSiteDBModel.FK_PSProjectTechTag_PSTechTags", "PSTechTags").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PSTechTag> PSTechTagReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PSTechTag>("PersonalSiteDBModel.FK_PSProjectTechTag_PSTechTags", "PSTechTags");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PSTechTag>("PersonalSiteDBModel.FK_PSProjectTechTag_PSTechTags", "PSTechTags", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PersonalSiteDBModel", Name="PSTechTag")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PSTechTag : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PSTechTag object.
        /// </summary>
        /// <param name="techTagID">Initial value of the techTagID property.</param>
        /// <param name="techName">Initial value of the techName property.</param>
        public static PSTechTag CreatePSTechTag(global::System.Int32 techTagID, global::System.String techName)
        {
            PSTechTag pSTechTag = new PSTechTag();
            pSTechTag.techTagID = techTagID;
            pSTechTag.techName = techName;
            return pSTechTag;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 techTagID
        {
            get
            {
                return _techTagID;
            }
            set
            {
                if (_techTagID != value)
                {
                    OntechTagIDChanging(value);
                    ReportPropertyChanging("techTagID");
                    _techTagID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("techTagID");
                    OntechTagIDChanged();
                }
            }
        }
        private global::System.Int32 _techTagID;
        partial void OntechTagIDChanging(global::System.Int32 value);
        partial void OntechTagIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String techName
        {
            get
            {
                return _techName;
            }
            set
            {
                OntechNameChanging(value);
                ReportPropertyChanging("techName");
                _techName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("techName");
                OntechNameChanged();
            }
        }
        private global::System.String _techName;
        partial void OntechNameChanging(global::System.String value);
        partial void OntechNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PersonalSiteDBModel", "FK_PSProjectTechTag_PSTechTags", "PSProjectTechTag")]
        public EntityCollection<PSProjectTechTag> PSProjectTechTags
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PSProjectTechTag>("PersonalSiteDBModel.FK_PSProjectTechTag_PSTechTags", "PSProjectTechTag");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PSProjectTechTag>("PersonalSiteDBModel.FK_PSProjectTechTag_PSTechTags", "PSProjectTechTag", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
